drupal:
    image: t0mk/d8-apache-dev
    ports:
        - "5555:80"
    volumes:
        - ./www:/app
    links:
        - drupaldb
    env_file: envvars

drupaldb:
    image: mysql:5.7
    volumes_from:
        - dbvolume
    env_file: envvars

dbvolume:
    image: busybox
    volumes: 
        - /var/lib/mysql


